### ISSUE TITLE
As a user I want to be able to add/remove cards from a deck and rearrange the order of the cards

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#41]
#### React
- [x] internetenemies/combatcritters-react#13
#### ts wrap
- [x] internetenemies/combatcritters-ts#9
#### API
- [x] #61

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

## Add card to deck acceptance test

**Assumptions: You are logged in, on the collection page, and already have a deck made**

1. Click on the "All" button in the inventory to display all cards in the game
2. Drag a card from the inventory and drop it in the deck
3. Click on the "Save" button
4. Logout (this is currently done by going to http://localhost:3000/login)
5. Log back in with your credentials
6. Navigate to the collection page
7. Select the deck with the saved card by clicking on the deck dropdown and selecting the deck
8. Assert that the card you previously added is in the deck

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

## Remove card from deck acceptance test

**Assumptions: You are logged in, on the collection page, and have a deck selected that has a card currently in it.**

1. Drag the card in your deck and drop it anywhere outside the deck
2. Assert that the card is no longer in the inventory
3. Click on the "Save" button
4. Logout (this is currently done by going to http://localhost:3000/login)
5. Log back in with your credentials
6. Navigate to the collection page
7. Select the deck with the deleted card by clicking on the deck dropdown and selecting the deck
8. Assert that the card you previously removed is still no longer in the deck
