### ISSUE TITLE
as a user I want to have options to sort/filter my card collection

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/CombatCritters#45]
### React
- [ ] InternetEnemies/combatcritters-react#19

**Comment by sahasra21321** [comment]
Hi, Can i take-up this task.

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

## Showing all cards acceptance test

**Assumptions: You are logged in and are on the collection page**

1. Click on the All button
2. Assert that a bunch of cards show up in the inventory...

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

## Sorting inventory cards acceptance test

**Assumptions: You are logged in and are on the colleciton page**

1. Click on the All button to show all cards in the game
2. Then click on the "Sort by ..." dropdown widget
3. Click on "Sort by Card Name"
4. Assert that the first card is "600 Frag Grenades" :)

**Comment by kivine99** [comment]
# React Frontend Acceptance Test

## Filtering inventory cards acceptance test

**Assumptions: You are logged in and on the collection page**

1. Click on the "All" button to show all cards in the game
2. Then click on the filter icon
3. Then toggle only the "Common" filter option
4. Assert all the cards displayed in the inventory are common (i.e. grey)
